name: craigshaw
favicon: null
layout_spectrum: 0.6727144257165492
typography_spectrum: 0.17116529564373195
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.16087372158654034
  lightness: 0.5947374133393168
  saturation: 0.9641789102461189
  rhythmicContrast: 0.19132065027952194
purpose: []
